"""
Regression tests: validate the current DuckDB state against the exported CSV snapshot
in datasets/exported-votes/.

These CSVs were generated by export_councillor_votes.py and contain verbatim motion
text, so matching is exact (meeting_url + motion_text + councillor_name) rather than
the approximate tally-based matching used for the horizonottawa CSVs.

Purpose: detect regressions if meetings are re-scraped and vote data changes.
"""

from pathlib import Path

import pandas as pd

from conftest import SLUG_TO_INITIAL

EXPORT_DIR = Path(__file__).resolve().parents[1] / "datasets" / "exported-votes"


def _load_exported_votes() -> pd.DataFrame:
    frames = [pd.read_csv(f) for f in sorted(EXPORT_DIR.glob("*.csv"))]
    df = pd.concat(frames, ignore_index=True)
    df["vote_normalised"] = df["vote"].map({"Yes": "for", "No": "against"})
    df["for_count"] = df["vote_tally"].str.extract(r"(\d+) Yes").astype(int)
    df["against_count"] = df["vote_tally"].str.extract(r"(\d+) No").astype(int)
    df["councillor_name"] = df["councillor"].map(SLUG_TO_INITIAL)
    return df


EXPORTED = _load_exported_votes()


def test_exported_vote_count_matches_db(db):
    """
    Total vote rows in the exported CSVs must equal total rows in the votes table.
    A mismatch indicates either unrecognised councillor names in the DB (e.g. 'and A. Troster'
    from a scraper parsing bug) or votes added to the DB after the snapshot was taken.
    """
    db_total = db.execute("SELECT COUNT(*) FROM votes").fetchone()[0]
    csv_total = len(EXPORTED)

    if csv_total != db_total:
        # surface which DB councillor names don't map to any known councillor
        from conftest import SLUG_TO_INITIAL
        known_initials = set(SLUG_TO_INITIAL.values())
        unknown = db.execute(
            """
            SELECT DISTINCT councillor_name, COUNT(*) as n
            FROM votes
            WHERE councillor_name NOT IN ({})
            GROUP BY councillor_name
            """.format(",".join(f"'{v}'" for v in known_initials))
        ).fetchall()
        detail = ""
        if unknown:
            detail = "\nUnrecognised councillor_name values in DB:\n" + "\n".join(
                f"  {name!r}  ({n} votes)" for name, n in unknown
            )

    assert csv_total == db_total, (
        f"Vote count mismatch: exported CSVs have {csv_total} rows, DB has {db_total}"
        + detail
    )


def test_no_missing_votes_in_db(db):
    """Every row in the exported CSVs must resolve to exactly one vote row in the DB."""
    failures = []

    for _, row in EXPORTED.iterrows():
        result = db.execute(
            """
            SELECT v.vote
            FROM votes v
            JOIN motions  m  ON v.motion_id  = m.motion_id
            JOIN meetings mt ON m.meeting_id = mt.meeting_id
            WHERE mt.source_url   = ?
              AND m.motion_text   = ?
              AND m.for_count     = ?
              AND m.against_count = ?
              AND v.councillor_name = ?
            """,
            [row.meeting_link, row.motion, int(row.for_count), int(row.against_count), row.councillor_name],
        ).fetchall()

        label = f"{row.councillor} | {row.date} | {str(row.motion)[:60]}"
        if len(result) == 0:
            failures.append(f"MISSING   {label}")
        elif len(result) > 1:
            failures.append(f"DUPLICATE {label}")

    assert not failures, (
        f"{len(failures)} row(s) not found in DB:\n" + "\n".join(failures)
    )


def test_vote_directions_unchanged(db):
    """Every vote direction in the exported CSVs must match the current DB value."""
    failures = []

    for _, row in EXPORTED.iterrows():
        result = db.execute(
            """
            SELECT v.vote
            FROM votes v
            JOIN motions  m  ON v.motion_id  = m.motion_id
            JOIN meetings mt ON m.meeting_id = mt.meeting_id
            WHERE mt.source_url   = ?
              AND m.motion_text   = ?
              AND m.for_count     = ?
              AND m.against_count = ?
              AND v.councillor_name = ?
            """,
            [row.meeting_link, row.motion, int(row.for_count), int(row.against_count), row.councillor_name],
        ).fetchone()

        if result and result[0] != row.vote_normalised:
            failures.append(
                f"{row.councillor} | {row.date} | {str(row.motion)[:60]}\n"
                f"  snapshot={row.vote_normalised}  db={result[0]}"
            )

    assert not failures, (
        f"{len(failures)} vote direction(s) changed since snapshot:\n"
        + "\n".join(failures)
    )
